### ISSUE TITLE
zsh compdef need compinit

### ISSUE THREAD

**Issue by mizchi** [azu/ni.zsh#13]
Need these setup to run

```zsh
autoload -Uz compinit
compinit
```

Error without compinit

```
~/.local/share/sheldon/repos/github.com/azu/ni.zsh/ni.zsh:510: command not found: compdef
```

**Comment by azu** [comment]
Thanks.

We have two options.

- Add documentation
  - [How do I enable Zsh completions? · mattmc3/antidote · Discussion #74](https://github.com/mattmc3/antidote/discussions/74)
- Detect `compinit` and enable auto load 
  - [nvm/bash_completion at 7b530edd3a2a3ebc976c455394f7245827194da7 · nvm-sh/nvm](https://github.com/nvm-sh/nvm/blob/7b530edd3a2a3ebc976c455394f7245827194da7/bash_completion#L83-L97)
  - nvm apply this approach
  - [zsh completion installation results in &quot;command not found: compdef&quot; · Issue #24430 · angular/angular-cli](https://github.com/angular/angular-cli/issues/24430)


However, `autoload -Uz compinit` has side-effect.
I prefer documentation.
